name: share_handler
description: A Flutter plugin to handle incoming shared text/media, as well as add share to suggestions/shortcuts.
repository: https://github.com/AboutShout/share_handler/tree/main/share_handler
publish_to: none
version: 0.0.16

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms: 
      android:
        default_package: share_handler_android 
      ios:
        default_package: share_handler_ios

dependencies:
  flutter:
    sdk: flutter
  share_handler_android:
    git:
      url: https://github.com/thesocialapp/share_handler.git
      path: share_handler_android
  share_handler_ios:
    git:
      url: https://github.com/thesocialapp/share_handler.git
      path: share_handler_ios
  share_handler_platform_interface:
    git:
      url: https://github.com/thesocialapp/share_handler.git
      path: share_handler_platform_interface

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  plugin_platform_interface: ^2.0.1
